Removed org.freedesktop.secrets dependency and removed GNOME category.
Azd325/gitkraken pull request #155
Opened 2021-01-11 13:09 UTC by sarvasana

People use this on KDE as well.

2021-01-11 15:59 UTC, Azd325 commented
What is your reason for removing `org.freedesktop.secrets`?

2021-01-11 16:44 UTC, sarvasana commented
Because it is not a dependency of GitKraken and forces KDE users to install GNOME Keyring or KeepassXC.

2021-01-12 16:22 UTC, Azd325 requested changes
Thanks for PR
I rechecked upstream and if `org.freedesktop.secrets` is defined as optional dependency I am happy to merge it.

2021-01-12 16:22 UTC, Azd325 commented on gitkraken/GitKraken.desktop
> -Categories=GNOME;GTK;Development;Documentation;
This category is from the upstream `.desktop` file, so I want to keep this.
Also this a related category to GTK. https://specifications.freedesktop.org/menu-spec/latest/apas02.html

2021-01-12 16:22 UTC, Azd325 commented on gitkraken/PKGBUILD
> -depends=('nss' 'libxtst' 'org.freedesktop.secrets' 'alsa-lib' 'libxss')
Can you add this as `optdepends` because the Debian Package offers this as a suggestion package?

2021-01-13 19:36 UTC, closed without merging